// @ts-nocheck
/** Dragonfall — DfData (motor TS, Fase 2). */
/** Dragonfall — DfData (motor TS, Fase 2). */
const heroDefs = [
    { id: 'vaughan', name: 'Rei Bomba', emoji: '🧙‍♂️', image: 'heroes/rei_bomba.png', ultimateName: 'Bomba Explosiva',
        ultimateDesc: 'Escolha um Campeão adversário. Ele perde 1 ponto de Poder. Se chegar a 0 será destruído.',
        ultimateType: 'targetEnemy' },
    { id: 'iceWitch', name: 'Frosty', emoji: '🧊', image: 'heroes/frosty.png', ultimateName: 'Congelar',
        ultimateDesc: 'Escolha um campeão adversário. Ele fica congelado por 3 rodadas. Até 3 usos.',
        ultimateType: 'targetEnemyFreeze' },
    { id: 'linguarudo', name: 'Florisbella', emoji: '🐸', image: 'heroes/florisbella.png', ultimateName: 'Fortalecer',
        ultimateDesc: 'Escolha um campeão aliado. Ele ganha +1 de poder.', ultimateType: 'targetAlly' },
    { id: 'pirate', name: 'Tina Punker', emoji: '🏴‍☠️', image: 'heroes/tina_punker.png', ultimateName: 'Investida',
        ultimateDesc: 'Escolha um campeão aliado. Ele pode realizar um ataque com ação livre neste turno.',
        ultimateType: 'targetAllyFreeAttack' },
    { id: 'euravia', name: 'Eurávia', emoji: '🔮', image: 'heroes/euravia.png', ultimateName: 'Conjuração',
        ultimateDesc: 'Compre uma carta imediatamente (ação livre). Pode usar até 4 vezes.',
        ultimateType: 'drawCard' },
    { id: 'ironGuard', name: 'Bastion', emoji: '🛡️', image: 'heroes/bastion.png', ultimateName: 'Proteção',
        ultimateDesc: 'Escolha um campeão aliado. Ele não pode ser atacado por uma rodada. Até 4 usos.',
        ultimateType: 'targetAllyShield' },
    { id: 'princesaSlime', name: 'Princesa Slime', emoji: '🧪', image: 'heroes/princesa_slime.png', ultimateName: 'Travessura',
        ultimateDesc: 'Escolha um Campeão aliado de Poder 1. Ele troca de lugar com um Campeão adversário (prioriza Poder 2, depois 3+, depois 1). Até 2 usos.',
        ultimateType: 'trickerySwap' },
    { id: 'thor', name: 'Thor', emoji: '⚡', image: 'heroes/thor.png', ultimateName: 'Trovoada',
        ultimateDesc: 'Todos os jogadores adversários descartam 1 carta da mão imediatamente. Até 3 usos.',
        ultimateType: 'thunderDiscard' },
    { id: 'jekiro', name: 'Jekiro', emoji: '🐲', image: 'heroes/jekiro.png', ultimateName: 'Fogo e Gelo',
        ultimateDesc: 'Afeta TODOS os Campeões adversários. Cada um tem 50% de chance de ser CONGELADO por 2 rodadas e 50% de chance de receber BOLA DE FOGO (-1 Poder). Até 3 usos.',
        ultimateType: 'fireAndIce' },
    { id: 'sangueDragao', name: 'Sangue de Dragão', emoji: '🩸', image: 'heroes/sangue_de_dragao.png', ultimateName: 'Invocar Dragão',
        ultimateDesc: 'Invoca um Dragão Cúbico no seu campo como ação livre. Até 3 usos.',
        ultimateType: 'summonDragon' },
    { id: 'gancho', name: 'Gancho', emoji: '⚓', image: 'heroes/gancho.png', ultimateName: 'Puxão',
        ultimateDesc: 'Puxa um Campeão adversário com Poder menor que 3 (65% chance de Poder 1, 35% de Poder 2) e o ROUBA permanentemente pro seu campo. Até 2 usos.',
        ultimateType: 'hook' },
    { id: 'paladino', name: 'Paladino', emoji: '🛡️', image: 'heroes/paladino.png', ultimateName: 'O Retorno do Herói',
        ultimateDesc: 'Traz de volta ao campo um Campeão de Poder 2 do seu descarte. Campeões com Habilidade Constante voltam aptos a usá-la; Habilidades Instantâneas não disparam nesta invocação. Até 3 usos.',
        ultimateType: 'resurrect' },
    { id: 'alquimista', name: 'Alquimista', emoji: '⚗️', image: 'heroes/alquimista.png', ultimateName: 'Poção Improvável',
        ultimateDesc: 'Escolha um Campeão seu: 60% de chance de +2 de Poder ou 40% de -1 (pode destruir se zerar). Até 3 usos.',
        ultimateType: 'potion' },
    { id: 'valmont', name: 'Valmont', emoji: '🧛', image: 'heroes/valmont.png', ultimateName: 'Vampirismo',
        ultimateDesc: 'Escolha um Campeão adversário com Poder 2 ou mais. Ele perde 1 Poder e um Campeão aliado aleatório ganha +1 Poder. Até 2 usos.',
        ultimateType: 'vampirism' },
    { id: 'tecnomago', name: 'Tecnomago', emoji: '🌀', image: 'heroes/tecnomago.png', ultimateName: 'Outra Dimensão',
        ultimateDesc: 'Escolha um Campeão adversário com Poder 2 ou menos. Ele é Banido do jogo (nem vai pro descarte) — você NÃO ganha PV. Até 2 usos.',
        ultimateType: 'banish' },
    { id: 'quimera', name: 'Quimera', emoji: '🐍', image: 'heroes/quimera.png', ultimateName: 'Envenenar',
        ultimateDesc: 'Escolha um Campeão adversário. Ele fica envenenado e será destruído em 2 rodadas (no início do seu 2º próximo turno). Até 3 usos.',
        ultimateType: 'poison' },
    { id: 'hercules', name: 'Hércules', emoji: '💪', image: 'heroes/hercules.png', ultimateName: 'Força Infinita',
        ultimateDesc: 'TODOS os seus Campeões aliados em campo ganham +1 de Poder permanente a cada rodada (igual ao Filhote de Dragão). Até 3 usos por partida.',
        ultimateType: 'infinitePower' },
    { id: 'sinistrela', name: 'Sinistrela', emoji: '😨', image: 'heroes/sinistrela.png', ultimateName: 'Amedrontar',
        ultimateDesc: 'Escolha um Campeão adversário com Poder 2 ou menos. Ele retorna à mão do dono com o Poder base. Até 2 usos.',
        ultimateType: 'scareReturn' },
    { id: 'estrelar', name: 'Estrelar', emoji: '⭐', image: 'heroes/estrelar.png', ultimateName: 'Cometa Estrelar',
        ultimateDesc: 'Um cometa cai no campo: TODOS os Campeões (aliados e adversários) perdem 1 de Poder. Você só ganha PV pelos Campeões adversários destruídos — destruir os seus próprios não dá PV. Até 3 usos.',
        ultimateType: 'cometStarfall' }
];
const cardDefs = [
    { name: "CAVALEIRO DA NOITE", power: 1, category: "champion", abilityType: "constant", abilityName: "Sem Honra",
        abilityDesc: "O Adversário Não ganha\nPonto de Vitória, ao\ndestruir esse Campeão.", onDestroy: "noHonor", onEnter: null, composedFace: true },
    { name: "REI CAVEIRA", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Sem Honra", abilityDesc: "O Adversário Não ganha\nPonto de Vitória, ao\ndestruir esse Campeão.",
        onDestroy: "noHonor", onEnter: null, composedFace: true },
    { name: "NOBRE ELFA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Defensor",
        abilityDesc: "Ao entrar em campo, recebe Proteção permanente.",
        onDestroy: null, onEnter: "defensor", composedFace: true },
    { name: "SIR DUNKAN", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Defensor",
        abilityDesc: "Ao entrar em campo, recebe Proteção permanente.",
        onDestroy: null, onEnter: "defensor", composedFace: true },
    { name: "GAMER", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Recompensa Dupla",
        abilityDesc: "Ao destruir um Campeão em combate, ganhe 2 pvs.",
        onDestroy: null, onEnter: null, constantEffect: "recompensaDupla", composedFace: true },
    { name: "ARCADIA", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Recompensa Dupla",
        abilityDesc: "Ao destruir um Campeão em combate, ganhe 2 pvs.",
        onDestroy: null, onEnter: null, constantEffect: "recompensaDupla", composedFace: true },
    { name: "TIGRE DE GELO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Rajada Congelante",
        abilityDesc: "Escolha um Campeão adversário. Ele ficará congelado.",
        onDestroy: null, onEnter: "rajadaCongelante", composedFace: true },
    { name: "MAGO DE GELO", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Rajada Congelante",
        abilityDesc: "Escolha um Campeão adversário. Ele ficará congelado.",
        onDestroy: null, onEnter: "rajadaCongelante", composedFace: true },
    { name: "HELA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Corromper",
        abilityDesc: "Escolha um Campeão aliado. Ele ficará corrompido, e o jogador adversário que o destruir, não receberá Ponto de vitória.",
        onDestroy: null, onEnter: "corromper", composedFace: true },
    { name: "MANDAGORA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Mordida Venenosa",
        abilityDesc: "Escolha um Campeão adversário. Ele ficará envenenado.",
        onDestroy: null, onEnter: "mordidaVenenosa", composedFace: true },
    { name: "VIPER", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Mordida Venenosa",
        abilityDesc: "Escolha um Campeão adversário. Ele ficará envenenado.",
        onDestroy: null, onEnter: "mordidaVenenosa", composedFace: true },
    { name: "VIOLÊNCIA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Grito de Guerra",
        abilityDesc: "Campeões aliados ganham Fúria, durante 1 rodada.",
        onDestroy: null, onEnter: "gritoDeGuerra", composedFace: true },
    { name: "BATEDOR FEROZ", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Grito de Guerra",
        abilityDesc: "Campeões aliados ganham Fúria, durante 1 rodada.",
        onDestroy: null, onEnter: "gritoDeGuerra", composedFace: true },
    { name: "AKASHA", power: 2, category: "champion", abilityType: "instant", abilityName: "Pesadelo",
        abilityDesc: "Escolha um Jogador. Ele não\npoderá fazer Saque Livre,\ndurante 1 rodada.", onDestroy: null,
        onEnter: "pesadelo", composedFace: true },
    { name: "SUCCUBUS", power: 1, category: "champion", abilityType: "instant", abilityName: "Pesadelo",
        abilityDesc: "Escolha um Jogador. Ele não\npoderá fazer Saque Livre,\ndurante 1 rodada.", onDestroy: null,
        onEnter: "pesadelo", composedFace: true },
    { name: "TAGARELA", power: 1, category: "champion", abilityType: "instant", abilityName: "Roubar",
        abilityDesc: "Pegue 1 carta aleatória da Mão do adversário.",
        onDestroy: null, onEnter: "roubar", composedFace: true },
    { name: "RAZIEL", power: 2, category: "champion", abilityType: "instant", abilityName: "Roubar",
        abilityDesc: "Pegue 1 carta aleatória da Mão do adversário.",
        onDestroy: null, onEnter: "roubar", composedFace: true },
    { name: "MAGA DO TEMPO", power: 1, category: "champion", abilityType: "instant", abilityName: "Desacelerar",
        abilityDesc: "O Jogador adversário faz 1 ação a menos no turno dele!",
        onDestroy: null, onEnter: "desacelerar", composedFace: true },
    { name: "WYVERN", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Invocar Dragão",
        abilityDesc: "Invoque o Campeão:\nFilhote de dragão, para seu\nCampo , como ação Livre.",
        onDestroy: null, onEnter: "invokeDragon", composedFace: true },
    { name: "FERAGROSS", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Invocar Dragão",
        abilityDesc: "Invoque o Campeão:\nFilhote de dragão, para seu\nCampo , como ação Livre.",
        onDestroy: null, onEnter: "invokeDragon", composedFace: true },
    { name: "LILITH", power: 1, category: "champion", abilityType: "instant", abilityName: "Bola de Fogo",
        abilityDesc: "Reduza o Poder de um Campeão\nadversário em 1 Ponto!",
        onDestroy: null, onEnter: "bolaDeFogo", composedFace: true },
    { name: "ELEMENTISTA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Bola de Fogo",
        abilityDesc: "Reduza o Poder de um Campeão\nadversário em 1 Ponto!",
        onDestroy: null, onEnter: "bolaDeFogo", composedFace: true },
    { name: "VEGA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Assassinar",
        abilityDesc: "Reduza o Poder de um Campeão P1 a zero!", onDestroy: null,
        onEnter: "assassinar", composedFace: true },
    { name: "MIRA OCULTA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Assassinar",
        abilityDesc: "Reduza o Poder de um Campeão P1 a zero!", onDestroy: null,
        onEnter: "assassinar", composedFace: true },
    { name: "A DUELISTA", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Sobrepujar",
        abilityDesc: "Nunca é destruída quando entra em Combate contra um Campeão com Poder igual.", onDestroy: null, onEnter: null, composedFace: true },
    { name: "POPPY", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Sobrepujar",
        abilityDesc: "Nunca é destruída quando entra em Combate contra um Campeão com Poder igual.", onDestroy: null, onEnter: null, composedFace: true },
    { name: "GAROU", power: 2, category: "champion", abilityType: "instant", abilityName: "Rapidez",
        abilityDesc: "Ao entrar em campo, concede +1 ação extra neste turno.", onDestroy: null,
        onEnter: "rapidez", composedFace: true },
    { name: "PISTOLEIRA NEON", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Rapidez",
        abilityDesc: "Ao entrar em campo, concede +1 ação extra neste turno.",
        onDestroy: null, onEnter: "rapidez", composedFace: true },
    { name: "FAUNO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Fortalecer",
        abilityDesc: "Acrescente +1 de Poder a um Campeão.", onDestroy: null,
        onEnter: "fortalecer", composedFace: true },
    { name: "GAIA", power: 2, category: "champion", abilityType: "instant", abilityName: "Fortalecer",
        abilityDesc: "Acrescente +1 de Poder a um Campeão.", onDestroy: null,
        onEnter: "fortalecer", composedFace: true },
    { name: "COME PEDRA", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Resistente",
        abilityDesc: "São necessárias 2 Ações para Atacar esse Campeão. Campeões com Investida não podem Atacá-lo.",
        onDestroy: null, onEnter: null, composedFace: true },
    { name: "CROCOLOSSO", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Resistente",
        abilityDesc: "São necessárias 2 Ações para Atacar esse Campeão. Campeões com Investida não podem Atacá-lo.",
        onDestroy: null, onEnter: null, composedFace: true },
    // DEVORAR (Tirânico, Carnivora): onEnter target-ally. Escolhe
    // um Campeão aliado, destrói, e SOMA o currentPower dele ao
    // currentPower do invocador. Se não houver aliado, fizzle
    // (o invocador entra com poder base).
    { name: "TIRÂNICO", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Devorar",
        abilityDesc: "Destrua um Campeão aliado em campo. Agora some o poder da carta destruída a esse Campeão.",
        onDestroy: null, onEnter: "devorar", composedFace: true },
    { name: "CARNIVORA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Devorar",
        abilityDesc: "Destrua um Campeão aliado em campo. Agora some o poder da carta destruída a esse Campeão.",
        onDestroy: null, onEnter: "devorar", composedFace: true },
    // RITUAL (Ômega, Tiamat): custo de invocação ALTERNATIVO.
    // Em vez de pagar Ações = Poder da carta, o jogador sacrifica
    // um aliado de Poder = summonRitual e invoca como Ação Livre.
    // É a ÚNICA forma de invocar essas cartas — sem aliado válido
    // não dá pra jogar. Veja summonFromHand pra fluxo.
    { name: "ÔMEGA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Ritual",
        abilityDesc: "Sacrifique um Campeão P1 no seu Campo, e invoque Ômega como Ação Livre.",
        onDestroy: null, onEnter: null, summonRitual: 1, composedFace: true },
    { name: "TIAMAT", power: 3, category: "champion", abilityType: "instant",
        abilityName: "Ritual Superior",
        abilityDesc: "Sacrifique um Campeão P2 no seu Campo, e invoque o Tiamat como Ação Livre.",
        onDestroy: null, onEnter: null, summonRitual: 2, composedFace: true },
    { name: "BOLA DE FOGO", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Bola de Fogo (Talento)",
        abilityDesc: "Reduza o Poder de um Campeão em 1 ponto.",
        onDestroy: null, onEnter: null, talentEffect: "bolaDeFogoTalento", composedFace: true },
    // EXPLOSÃO — Talento ofensivo. Custo 1 (igual à arte da
    // carta). Reduz 2 de Poder de um Campeão adversário; se
    // chegar a 0, é destruído. Respeita Proteção Divina.
    { name: "EXPLOSÃO", power: 1, category: "talent", abilityType: "talent",
        abilityName: "Explosão (Talento)",
        abilityDesc: "Reduza o Poder de um Campeão adversário em 2 pontos.",
        onDestroy: null, onEnter: null, talentEffect: "explosao", composedFace: true },
    // ZERO ABSOLUTO — Talento de controle. Custo 0. Congela um
    // Campeão adversário por 3 rodadas. Se o alvo JÁ está
    // congelado, é destruído (combo brutal).
    { name: "ZERO ABSOLUTO", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Zero Absoluto (Talento)",
        abilityDesc: "Custo 0. Congele um Campeão adversário por 3 rodadas. Se já estiver Congelado, é destruído.",
        onDestroy: null, onEnter: null, talentEffect: "zeroAbsoluto", composedFace: true },
    { name: "AMEDRONTAR", power: 0, category: "talent", abilityType: "talent", abilityName: "Amedrontar (Talento)",
        abilityDesc: "Escolha um campeão adversário. Ele retornará à mão do jogador afetado.",
        onDestroy: null, onEnter: null, talentEffect: "medoTalento", composedFace: true },
    // Cartas REAÇÃO: gameplay-wise continuam sendo `category:"talent"`
    // (a engine consome `talentEffect` igual aos outros talentos),
    // mas têm `subcategory:"reaction"` pra Lista de Cartas separá-las
    // numa aba própria e pra rotulação correta no jogo. Diferença
    // de regra: SÓ podem ser usadas FORA do seu turno (reativas).
    { name: "BLOQUEAR ATAQUE", power: 0, category: "talent", subcategory: "reaction", abilityType: "talent",
        abilityName: "Bloquear Ataque (Reação)",
        abilityDesc: "Cancele um ataque contra seu Campeão.",
        onDestroy: null, onEnter: null, talentEffect: "bloquearAtaque", composedFace: true },
    { name: "PROTEÇÃO DIVINA", power: 0, category: "talent", subcategory: "reaction", abilityType: "talent",
        abilityName: "Proteção Divina (Reação)",
        abilityDesc: "Impeça o Adversário de reduzir Poder de seu Campeão.",
        onDestroy: null, onEnter: null, talentEffect: "protecaoDivina", composedFace: true },
    { name: "CANCELAR ULTIMATE", power: 0, category: "talent", subcategory: "reaction", abilityType: "talent",
        abilityName: "Cancelar Ultimate (Reação)",
        abilityDesc: "Cancele a Ultimate de um Herói.",
        onDestroy: null, onEnter: null, talentEffect: "cancelarUltimate", composedFace: true },
    { name: "EXAUSTÃO", power: 0, category: "talent", subcategory: "reaction", abilityType: "talent",
        abilityName: "Exaustão (Reação)",
        abilityDesc: "Cancele a Habilidade instantânea de um Campeão.",
        onDestroy: null, onEnter: null, talentEffect: "exaustao", composedFace: true },
    { name: "CONTRAMÁGICA", power: 0, category: "talent", subcategory: "reaction", abilityType: "talent",
        abilityName: "Contramágica (Reação)",
        abilityDesc: "Cancele uma Carta Talento do adversário.",
        onDestroy: null, onEnter: null, talentEffect: "contramagica", composedFace: true },
    { name: "FORTALECER", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Fortalecer (Talento)",
        abilityDesc: "Escolha um campeão aliado, ele ganhará 1 Ponto de Poder.",
        onDestroy: null, onEnter: null, talentEffect: "fortalecerTalento", composedFace: true },
    { name: "DUPLICAR", power: 1, category: "talent", abilityType: "talent",
        abilityName: "Duplicar (Talento)",
        abilityDesc: "Escolha um Campeão aliado em campo, com Poder 2. Ele será duplicado!",
        onDestroy: null, onEnter: null, talentEffect: "doppelganger", composedFace: true },
    { name: "BARREIRA", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Barreira (Talento)",
        abilityDesc: "TODOS os Campeões aliados ganham Barreira durante 2 rodadas, ficando resistentes a redução de Poder.",
        onDestroy: null, onEnter: null, talentEffect: "barreira", composedFace: true },
    { name: "BAFORADA VENENOSA", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Baforada Venenosa (Talento)",
        abilityDesc: "Escolha um Campeão adversário. Ele ficará Envenenado!",
        onDestroy: null, onEnter: null, talentEffect: "baforadaVenenosa", composedFace: true },
    { name: "ACELERAÇÃO", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Aceleração (Talento)",
        abilityDesc: "Faça 1 ação adicional durante este turno.",
        onDestroy: null, onEnter: null, talentEffect: "aceleracao", composedFace: true },
    { name: "MÍSSEIS MÁGICOS", power: 1, category: "talent", abilityType: "talent",
        abilityName: "Mísseis Mágicos (Talento)",
        abilityDesc: "Campeões do adversário são atingidos por mísseis que tem 60% de Chance de reduzir 1 ponto de Poder.",
        onDestroy: null, onEnter: null, talentEffect: "missemagicos", composedFace: true },
    // Lote talentos v1.49.81 — custo 0, faces compostas.
    { name: "ARSENAL DE GUERRA", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Arsenal de Guerra (Talento)",
        abilityDesc: "Compre 2 cartas como ação livre.",
        onDestroy: null, onEnter: null, talentEffect: "arsenalDeGuerra", composedFace: true },
    { name: "INVESTIDA", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Investida (Talento)",
        abilityDesc: "Escolha um Campeão aliado e ele fará um Ataque como ação Livre.",
        onDestroy: null, onEnter: null, talentEffect: "investidaTalento", composedFace: true },
    { name: "GRITO DE GUERRA", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Grito de Guerra (Talento)",
        abilityDesc: "Campeões aliados ganham fúria durante 1 rodada, recebendo +1 de Poder.",
        onDestroy: null, onEnter: null, talentEffect: "gritoDeGuerraTalento", composedFace: true },
    { name: "PRISÃO PRISMÁTICA", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Prisão Prismática (Talento)",
        abilityDesc: "Escolha um campeão adversário, e ele deverá fazer 2 ações para atacar.",
        onDestroy: null, onEnter: null, talentEffect: "prisaoPrismaticaTalento", composedFace: true },
    { name: "TORNADO DE FOGO", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Tornado de Fogo (Talento)",
        abilityDesc: "Escolha 1 Campeão adversário. Ele perderá 1 ponto de Poder por rodada.",
        onDestroy: null, onEnter: null, talentEffect: "tornadoDeFogo", composedFace: true },
    { name: "MALDIÇÃO DOS SETE MARES", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Maldição dos Sete Mares (Talento)",
        abilityDesc: "O Próximo Campeão que o adversário invocar, não terá Habilidade.",
        onDestroy: null, onEnter: null, talentEffect: "maldicaoSeteMaresTalento", composedFace: true },
    { name: "TROCA DE LUGAR", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Troca de Lugar (Talento)",
        abilityDesc: "Escolha um Campeão aliado P1 e troque por um campeão do adversário P2.",
        onDestroy: null, onEnter: null, talentEffect: "trocaDeLugar", composedFace: true },
    { name: "TÉCNICAS DE COMBATE", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Técnicas de Combate (Talento)",
        abilityDesc: "Campeões aliados poderão vencer combates contra campeões com poder igual, durante 1 rodada.",
        onDestroy: null, onEnter: null, talentEffect: "tecnicasDeCombateTalento", composedFace: true },
    // Lote talentos v1.49.82 — custo 0, faces compostas.
    { name: "PODRIDÃO", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Podridão (Talento)",
        abilityDesc: "Contamine até 4 cartas do baralho do adversário. Elas ficarão inúteis.",
        onDestroy: null, onEnter: null, talentEffect: "podridaoTalento", composedFace: true },
    { name: "RESSUSCITAR", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Ressuscitar (Talento)",
        abilityDesc: "O último Campeão P2 seu destruído, retorna a seu campo.",
        onDestroy: null, onEnter: null, talentEffect: "ressuscitarTalento", composedFace: true },
    { name: "CORROMPER", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Corromper (Talento)",
        abilityDesc: "Escolha um Campeão. O adversário não ganhará PVs ao destruí-lo.",
        onDestroy: null, onEnter: null, talentEffect: "corromperTalento", composedFace: true },
    { name: "CHUVA DE COMETAS", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Chuva de Cometas (Talento)",
        abilityDesc: "Todos os Campeões em campo, seus e do adversário perdem 1 ponto de Poder.",
        onDestroy: null, onEnter: null, talentEffect: "chuvaDeCometas", composedFace: true },
    { name: "TRANSFORMAR EM BICHINHO", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Transformar em Bichinho (Talento)",
        abilityDesc: "Escolha um Campeão. O poder dele será reduzido pela metade, arredondado para baixo. Não funciona em Campeões P1.",
        onDestroy: null, onEnter: null, talentEffect: "transformarBichinhoTalento", composedFace: true },
    { name: "DESACELERAR", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Desacelerar (Talento)",
        abilityDesc: "O jogador adversário faz 1 ação a menos no turno dele.",
        onDestroy: null, onEnter: null, talentEffect: "desacelerarTalento", composedFace: true },
    // Lote talentos v1.49.83 — custo 0, faces compostas.
    { name: "ENFRAQUECER", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Enfraquecer (Talento)",
        abilityDesc: "Escolha um Campeão. O Jogador adversário perde 1 PV.",
        onDestroy: null, onEnter: null, talentEffect: "enfraquecerTalento", composedFace: true },
    { name: "TERREMOTO", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Terremoto (Talento)",
        abilityDesc: "Destrua 3 espaços do Campo do adversário, durante 3 rodadas.",
        onDestroy: null, onEnter: null, talentEffect: "terremotoTalento", composedFace: true },
    { name: "INVOCAR DRAGÃO", power: 0, category: "talent", abilityType: "talent",
        abilityName: "Invocar Dragão (Talento)",
        abilityDesc: "Invoque o Campeão FILHOTE DE DRAGÃO para seu campo.",
        onDestroy: null, onEnter: null, talentEffect: "invocarDragaoTalento", composedFace: true },
    // TRANSFORMAR EM BICHINHO (Bola de Pelos / Aprendiz de Arquimago):
    // ao invocar, escolhe um Campeão adversário com Poder ≥ 2.
    // 80% sucesso → vira BICHINHO FOFINHO (Poder = floor(orig/2),
    // sem habilidade). 20% falha → vira O CHEFÃO
    // (Poder = orig + 1, sem habilidade).
    { name: "BOLA DE PELOS", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Transformar em Bichinho",
        abilityDesc: "Reduza o Poder de um Campeão pela metade, transformando-o em Bichinho, ou em Alguma coisa pior.",
        onDestroy: null, onEnter: "transformarBichinho", composedFace: true },
    { name: "APRENDIZ DE ARQUIMAGO", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Transformar em Bichinho",
        abilityDesc: "Reduza o Poder de um Campeão pela metade, transformando-o em Bichinho, ou em Alguma coisa pior.",
        onDestroy: null, onEnter: "transformarBichinho", composedFace: true },
    // MALDIÇÃO DOS SETE MARES (BOLHAS / TUBARÃO BORRIFANTE):
    { name: "BOLHAS", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Maldição dos Sete Mares",
        abilityDesc: "O próximo campeão que seu Adversário invocar, não terá habilidade.",
        onDestroy: null, onEnter: "maldicaoSeteMares", composedFace: true },
    { name: "TUBARÃO BORRIFANTE", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Maldição dos Sete Mares",
        abilityDesc: "O próximo campeão que seu Adversário invocar, não terá habilidade.",
        onDestroy: null, onEnter: "maldicaoSeteMares", composedFace: true },
    // IMITAR (WU-KONG / ENIGMA): escolhe um Campeão ALIADO
    // (excluindo o próprio invocador) e COPIA a habilidade dele
    // (onEnter, onDestroy, abilityType, abilityName, abilityDesc).
    // Se a habilidade copiada tem onEnter, executa imediatamente.
    // Se for constante (Sobrepujar/Resistente/Sem Honra/etc.),
    // o invocador adquire essa habilidade permanentemente.
    { name: "WU-KONG", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Imitar",
        abilityDesc: "Tem a Habilidade igual a de um Campeão Aliado a sua escolha.",
        onDestroy: null, onEnter: "imitar", composedFace: true },
    { name: "ENIGMA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Imitar",
        abilityDesc: "Tem a Habilidade igual a de um Campeão Aliado a sua escolha.",
        onDestroy: null, onEnter: "imitar", composedFace: true },
    // VINGANÇA (FURIOSA / GRIZZLY): onDestroy constante.
    // Quando destruída, um Campeão ALEATÓRIO do adversário perde
    // 1 ponto de Poder (se chegar a 0, é destruído sem PV pro
    // adversário). Não dispara sob Silêncio.
    { name: "FURIOSA", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Vingança",
        abilityDesc: "Após morrer, um Campeão aleatório do adversário, terá 1 ponto de Poder reduzido.",
        onDestroy: "vinganca", onEnter: null, composedFace: true },
    { name: "GRIZZLY", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Vingança",
        abilityDesc: "Após morrer, um Campeão aleatório do adversário, terá 1 ponto de Poder reduzido.",
        onDestroy: "vinganca", onEnter: null, composedFace: true },
    // LEGADO (BARBALONGA / BEATRIX): onDestroy constante.
    // Quando destruída, um Campeão ALIADO aleatório ganha +1
    // ponto de Poder. Resistentes são pulados (não podem ganhar
    // Poder). Não dispara sob Silêncio.
    { name: "BARBALONGA", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Legado",
        abilityDesc: "Após a morrer, um Campeão aliado aleatório ganhará 1 ponto de Poder!",
        onDestroy: "legado", onEnter: null, composedFace: true },
    { name: "BEATRIX", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Legado",
        abilityDesc: "Após a morrer, um Campeão aliado aleatório ganhará 1 ponto de Poder!",
        onDestroy: "legado", onEnter: null, composedFace: true },
    // NECROMANCIA (LICH / MÁSCARA DA MORTE): onEnter instantânea.
    // Mostra até 4 cartas aleatórias do DESCARTE pro jogador
    // escolher 1, que volta pra MÃO. As outras 3 ficam no
    // descarte. Se a mão estiver cheia, a carta escolhida vai
    // pra mão MESMO (sem checar limite — comportamento intencional
    // de uma habilidade poderosa). Se o descarte estiver vazio,
    // fizzle silencioso. IA escolhe a carta de maior valor.
    { name: "LICH", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Necromancia",
        abilityDesc: "Escolha 1 carta dentre as últimas 4 cartas que você usou, e ela retornará para sua Mão.",
        onDestroy: null, onEnter: "necromancia", composedFace: true },
    { name: "MÁSCARA DA MORTE", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Necromancia",
        abilityDesc: "Escolha 1 carta dentre as últimas 4 cartas que você usou, e ela retornará para sua Mão.",
        onDestroy: null, onEnter: "necromancia", composedFace: true },
    { name: "GRISELDA", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Investida",
        abilityDesc: "Pode Atacar como Ação Livre. Não pode Atacar Campeões Resistentes.",
        onDestroy: null, onEnter: null, constantEffect: "investida", composedFace: true },
    { name: "CAVALEIRA BRINQUEDO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Troca Injusta",
        abilityDesc: "Troque essa Campeã, com um Campeão aleatório de Poder 2 do Adversário.",
        onDestroy: null, onEnter: "trocaInjusta", composedFace: true },
    { name: "PANDA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Ursificação",
        abilityDesc: "Transforme um Campeão aliado em um Urso gigante e pesado. Ele ganha +2 de Poder.",
        onDestroy: null, onEnter: "ursificacao", composedFace: true },
    { name: "MENINA URSO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Ursificação",
        abilityDesc: "Transforme um Campeão aliado em um Urso gigante e pesado. Ele ganha +2 de Poder.",
        onDestroy: null, onEnter: "ursificacao", composedFace: true },
    { name: "OLAF", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Fúria",
        abilityDesc: "Ao entrar em campo, ganha +1 de Poder por 1 rodada (status Fúria).",
        onDestroy: null, onEnter: "furia", composedFace: true },
    { name: "URSA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Fúria",
        abilityDesc: "Ao entrar em campo, ganha +1 de Poder por 1 rodada (status Fúria).",
        onDestroy: null, onEnter: "furia", composedFace: true },
    { name: "ARCANJO", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Guardião",
        abilityDesc: "Campeões aliados ganham Proteção!",
        onDestroy: null, onEnter: "guardiao", composedFace: true },
    { name: "PANTEÃO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Guardião",
        abilityDesc: "Campeões aliados ganham Proteção!",
        onDestroy: null, onEnter: "guardiao", composedFace: true },
    { name: "TOXINA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Fumaça Tóxica",
        abilityDesc: "Os Campeões adversários ficam vulneráveis e são destruídos quando recebem qualquer redução de poder.",
        onDestroy: null, onEnter: "fumacaToxica", composedFace: true },
    { name: "MARTIS", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Fumaça Tóxica",
        abilityDesc: "Os Campeões adversários ficam vulneráveis e são destruídos quando recebem qualquer redução de poder.",
        onDestroy: null, onEnter: "fumacaToxica", composedFace: true },
    { name: "ANTI-MAGOS", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Aura Anti-Magia",
        abilityDesc: "Ao entrar, recebe Barreira permanente. Bloqueia redução de Poder sem perder o status.",
        onDestroy: null, onEnter: "auraAntiMagia", composedFace: true },
    { name: "SOLDADO DO FUTURO", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Aura Anti-Magia",
        abilityDesc: "Ao entrar, recebe Barreira permanente. Bloqueia redução de Poder sem perder o status.",
        onDestroy: null, onEnter: "auraAntiMagia", composedFace: true },
    { name: "CALCIFER", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Incendiar",
        abilityDesc: "Escolha um Campeão adversário. Ele ficará Em Chamas, perdendo 1 ponto de poder por rodada.",
        onDestroy: null, onEnter: "incendiar", composedFace: true },
    { name: "EFREET", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Incendiar",
        abilityDesc: "Escolha um Campeão adversário. Ele ficará Em Chamas, perdendo 1 ponto de poder por rodada.",
        onDestroy: null, onEnter: "incendiar", composedFace: true },
    { name: "MINOTAURO", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Crescimento",
        abilityDesc: "Ganha +1 de Poder, a cada\nrodada completa que permanecer\nno seu campo.",
        onDestroy: null, onEnter: null, composedFace: true },
    { name: "GUARDIÃO DA CHAVE", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Crescimento",
        abilityDesc: "Ganha +1 de Poder, a cada\nrodada completa que permanecer\nno seu campo.",
        onDestroy: null, onEnter: null, composedFace: true },
    { name: "ZEUS", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Raio Duplo",
        abilityDesc: "Reduza em 1 ponto o poder de dois campeões do oponente. Você Não ganha Pvs por isso.",
        onDestroy: null, onEnter: "raioDuplo", composedFace: true },
    { name: "PATRULHEIRA ESPACIAL", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Desacelerar",
        abilityDesc: "O Jogador adversário faz 1 ação a menos no turno dele!",
        onDestroy: null, onEnter: "desacelerar", composedFace: true },
    { name: "CRISÁLIDA", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Inspirar",
        abilityDesc: "Campeões adjacentes tem +1 de Poder, enquanto a Crisálida estiver em campo.",
        onDestroy: null, onEnter: null, constantEffect: "inspirar", composedFace: true },
    { name: "BARGANHA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Corromper",
        abilityDesc: "Escolha um Campeão aliado. Ele ficará corrompido, e o jogador adversário que o destruir, não receberá Ponto de vitória.",
        onDestroy: null, onEnter: "corromper", composedFace: true },
    { name: "KUMIKO", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Investida",
        abilityDesc: "Pode Atacar como Ação Livre. Não pode Atacar Campeões Resistentes.",
        onDestroy: null, onEnter: null, constantEffect: "investida", composedFace: true },
    { name: "JOVEM ARTÍFICE", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Forja",
        abilityDesc: "Sempre que esse campeão for invocado, você ganha uma carta.",
        onDestroy: null, onEnter: "forja", composedFace: true },
    { name: "TINKER", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Forja",
        abilityDesc: "Sempre que esse campeão for invocado, você ganha uma carta.",
        onDestroy: null, onEnter: "forja", composedFace: true },
    { name: "CENTAURO GUERREIRO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Técnicas de Combate",
        abilityDesc: "Ao entrar em campo, todos os outros Campeões aliados ganham Sobrepujar por 1 rodada.",
        onDestroy: null, onEnter: "tecnicasDeCombate", composedFace: true },
    { name: "MULAN", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Técnicas de Combate",
        abilityDesc: "Ao entrar em campo, todos os outros Campeões aliados ganham Sobrepujar por 1 rodada.",
        onDestroy: null, onEnter: "tecnicasDeCombate", composedFace: true },
    { name: "CAÇADORA DE RECOMPENSAS", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Roleta Russa",
        abilityDesc: "Ao entrar em campo, destrói 1 Campeão aleatório em qualquer campo.",
        onDestroy: null, onEnter: "roletaRussa", composedFace: true },
    { name: "ERIS A PIRATA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Roleta Russa",
        abilityDesc: "Ao entrar em campo, destrói 1 Campeão aleatório em qualquer campo.",
        onDestroy: null, onEnter: "roletaRussa", composedFace: true },
    { name: "SHINOBI", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Podridão",
        abilityDesc: "Ao entrar, contamina até 4 cartas no baralho inimigo. Cartas podres custam 0 mas não têm efeito.",
        onDestroy: null, onEnter: "podridao", composedFace: true },
    { name: "KORUSBELLA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Podridão",
        abilityDesc: "Ao entrar, contamina até 4 cartas no baralho inimigo. Cartas podres custam 0 mas não têm efeito.",
        onDestroy: null, onEnter: "podridao", composedFace: true },
    { name: "TEMPESTA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Raio Duplo",
        abilityDesc: "Reduza em 1 ponto o poder de dois campeões do oponente. Você Não ganha Pvs por isso.",
        onDestroy: null, onEnter: "raioDuplo", composedFace: true },
    // INSPIRAR (PRINCESA AURORA): constante.
    { name: "PRINCESA AURORA", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Inspirar",
        abilityDesc: "Campeões adjacentes tem +1 de Poder, enquanto a Princesa Aurora estiver em campo.",
        onDestroy: null, onEnter: null, constantEffect: "inspirar", composedFace: true },
    // MURALHA NATIVA: +1 Poder fora do turno, regenera.
    { name: "CAVALEIRO JURAMENTADO", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Muralha",
        abilityDesc: "Enquanto você estiver fora do turno, ganha +1 de Poder. No início do seu turno, perde o ponto de poder recebido.",
        onDestroy: null, onEnter: null, constantEffect: "muralha", muralhaNativa: true, composedFace: true },
    { name: "ALEXANDER", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Muralha",
        abilityDesc: "Enquanto você estiver fora do turno, ganha +1 de Poder. No início do seu turno, perde o ponto de poder recebido.",
        onDestroy: null, onEnter: null, constantEffect: "muralha", muralhaNativa: true, composedFace: true },
    // SEPARAR: divide inimigo P2 em 2 cópias P1.
    { name: "APRENDIZ DE FEITICEIRA", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Separar",
        abilityDesc: "Ao entrar em campo, escolha um Campeão adversário com Poder 2. Ele se divide em 2 cópias idênticas com Poder 1 cada, mantendo as mesmas habilidades.",
        onDestroy: null, onEnter: "separar", composedFace: true },
    { name: "RONIN", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Separar",
        abilityDesc: "Ao entrar em campo, escolha um Campeão adversário com Poder 2. Ele se divide em 2 cópias idênticas com Poder 1 cada, mantendo as mesmas habilidades.",
        onDestroy: null, onEnter: "separar", composedFace: true },
    // PRISÃO PRISMÁTICA: atacar com o alvo custa sempre 2 ações.
    { name: "GUERREIRO CÚBICO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Prisão Prismática",
        abilityDesc: "Ao entrar em campo, escolha 1 Campeão adversário. Ele fica preso numa Prisão Prismática: atacar com ele custa sempre 2 ações.",
        onDestroy: null, onEnter: "prisaoPrismatica", composedFace: true },
    { name: "GUERREIRO CÚBICO CORROMPIDO", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Prisão Prismática",
        abilityDesc: "Ao entrar em campo, escolha 1 Campeão adversário. Ele fica preso numa Prisão Prismática: atacar com ele custa sempre 2 ações.",
        onDestroy: null, onEnter: "prisaoPrismatica", composedFace: true },
    // DESAFIANTE: +2 Poder enquanto sozinho no campo.
    { name: "ELFO GLADIADOR", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Desafiante",
        abilityDesc: "Enquanto este Campeão for o único no seu campo, ele tem +2 de Poder.",
        onDestroy: null, onEnter: null, constantEffect: "desafiante", composedFace: true },
    { name: "PUNHOS DE FERRO", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Desafiante",
        abilityDesc: "Enquanto este Campeão for o único no seu campo, ele tem +2 de Poder.",
        onDestroy: null, onEnter: null, constantEffect: "desafiante", composedFace: true },
    // ENFRAQUECER: adversário −1 PV.
    { name: "ASSOMBRAÇÃO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Enfraquecer",
        abilityDesc: "Ao entrar em campo, o jogador adversário perde 1 Ponto de Vitória.",
        onDestroy: null, onEnter: "enfraquecer", composedFace: true },
    { name: "DEMÔNIO ALADO", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Enfraquecer",
        abilityDesc: "Ao entrar em campo, o jogador adversário perde 1 Ponto de Vitória.",
        onDestroy: null, onEnter: "enfraquecer", composedFace: true },
    // ENERGIZAR: +1 uso de Ultimate.
    { name: "AMIGÃO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Energizar",
        abilityDesc: "Ao entrar em campo, você ganha 1 Energia: +1 uso de Ultimate nesta partida.",
        onDestroy: null, onEnter: "energizar", composedFace: true },
    { name: "ELFAS GÊMEAS", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Energizar",
        abilityDesc: "Ao entrar em campo, você ganha 1 Energia: +1 uso de Ultimate nesta partida.",
        onDestroy: null, onEnter: "energizar", composedFace: true },
    // TERREMOTO: 3 Buracos no campo adversário por 3 rodadas.
    { name: "ELEFANTO", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Terremoto",
        abilityDesc: "Destrua 3 espaços do Campo do adversário, durante 3 rodadas.",
        onDestroy: null, onEnter: "terremoto", composedFace: true },
    { name: "MECHA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Terremoto",
        abilityDesc: "Destrua 3 espaços do Campo do adversário, durante 3 rodadas.",
        onDestroy: null, onEnter: "terremoto", composedFace: true },
    // LAÇO DE SANGUE: ao destruir em combate, aliado aleatório +1 Poder.
    { name: "CAVALEIRO SANGUINÁRIO", power: 1, category: "champion", abilityType: "constant",
        abilityName: "Laço de Sangue",
        abilityDesc: "Sempre que atacar e destruir um Campeão em COMBATE, um Campeão aliado aleatório ganha +1 de Poder.",
        onDestroy: null, onEnter: null, constantEffect: "lacoDeSangue", composedFace: true },
    { name: "SCARLET", power: 2, category: "champion", abilityType: "constant",
        abilityName: "Laço de Sangue",
        abilityDesc: "Sempre que atacar e destruir um Campeão em COMBATE, um Campeão aliado aleatório ganha +1 de Poder.",
        onDestroy: null, onEnter: null, constantEffect: "lacoDeSangue", composedFace: true },
    // CHARME: rouba inimigo por 2 rodadas (não ataca).
    { name: "EUGINE", power: 1, category: "champion", abilityType: "instant",
        abilityName: "Charme",
        abilityDesc: "Um Campeão do Adversário fica enfeitiçado e vem para seu campo durante 2 rodadas.",
        onDestroy: null, onEnter: "charme", composedFace: true },
    { name: "WISP A TELEPATA", power: 2, category: "champion", abilityType: "instant",
        abilityName: "Charme",
        abilityDesc: "Um Campeão do Adversário fica enfeitiçado e vem para seu campo durante 2 rodadas.",
        onDestroy: null, onEnter: "charme", composedFace: true },
    // TOKENS de Ursificação / Transformar em Bichinho. `hidden:true`
    // mantém estas cartas FORA da Lista de Cartas E FORA do baralho.
    { name: "BANJO", power: 0, category: "champion", abilityType: "constant",
        abilityName: "Pesado Demais",
        abilityDesc: "Precisa de 2 Ações para Atacar. Não pode Atacar Campeões Resistentes.",
        onDestroy: null, onEnter: null, hidden: true, composedFace: true },
    { name: "BICHINHO FOFINHO", power: 0, category: "champion", abilityType: "constant",
        abilityName: "Fofura",
        abilityDesc: "Ser fofo é sua principal arma. Sem habilidade.",
        onDestroy: null, onEnter: null, hidden: true, composedFace: true },
    { name: "O CHEFÃO", power: 0, category: "champion", abilityType: "constant",
        abilityName: "Ameaça Eminente",
        abilityDesc: "Gosta de uma boa briga! Sem habilidade.",
        onDestroy: null, onEnter: null, hidden: true, composedFace: true },
];
const babyDragonDef = { name: "FILHOTE DE DRAGÃO", power: 1, category: "champion", abilityType: "constant",
    abilityName: "Crescimento",
    abilityDesc: "Ganha +1 de Poder, a cada\nrodada completa que permanecer\nno seu campo.",
    onDestroy: null, onEnter: null, composedFace: true };
;
const cubicDragonDef = { name: "DRAGÃO AZUL", power: 2, category: "champion", abilityType: "constant",
    abilityName: "Crescimento",
    abilityDesc: "Ganha +1 de Poder, a cada\nrodada completa que permanecer\nno seu campo.",
    onDestroy: null, onEnter: null, composedFace: true };
;
const DfData = {
    heroDefs,
    cardDefs,
    babyDragonDef,
    cubicDragonDef,
    /** Renomes de carta: baralhos antigos. */
    cardRenameMap: Object.freeze({
        VOID: "AKASHA",
        "DRAGÃO CÚBICO": "DRAGÃO AZUL",
        DIANA: "PANDA",
        OVELINA: "MENINA URSO",
        BOLT: "TEMPESTA",
        // AMIGÃO→PANTEÃO removido: AMIGÃO é carta nova (Energizar).
        // MEDUSA foi renomeada para MANDAGORA (mesma carta, arte nova).
        // O alias antigo MANDAGORA→MARTIS foi removido: o nome agora
        // pertence à ex-MEDUSA, então mantê-lo desviaria a carta errada.
        MEDUSA: "MANDAGORA",
        "FÚRIA VERMELHA": "FURIOSA",
        "JAY O BRIGÃO": "FURIOSA",
        FIONA: "GRIZZLY",
        ONI: "GRIZZLY",
        LEONA: "GRIZZLY",
        "SIR DUCKAN": "SIR DUNKAN",
        "PÉ GRANDE": "MAGO DE GELO",
        // ALIEN→TARTARUGA VENENOSA e FLY→FURIOSA removidos: os destinos
        // saíram do jogo, então o alias apontaria para carta inexistente.
        LUCIAN: "ARCADIA",
        "BATEDOR URUK": "BATEDOR FEROZ",
        EXPLOSAO: "EXPLOSÃO",
        DOPPELGANGER: "DUPLICAR",
        "MISSEIS MÁGICOS": "MÍSSEIS MÁGICOS",
        JOKER: "ERIS A PIRATA",
    }),
    resolveCardName(name) {
        const n = String(name || "").trim();
        if (!n)
            return n;
        return DfData.cardRenameMap[n] || n;
    },
    dragonTokenDef(name) {
        const resolved = DfData.resolveCardName(name);
        return resolved === "DRAGÃO AZUL" ? cubicDragonDef : babyDragonDef;
    },
};
export { DfData };
