/** Dragonfall — DfData (motor TS, Fase 2). */
declare const DfData: {
    heroDefs: {
        id: string;
        name: string;
        emoji: string;
        image: string;
        ultimateName: string;
        ultimateDesc: string;
        ultimateType: string;
    }[];
    cardDefs: ({
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: string;
        onEnter: any;
        composedFace: boolean;
        constantEffect?: undefined;
        summonRitual?: undefined;
        talentEffect?: undefined;
        subcategory?: undefined;
        hidden?: undefined;
    } | {
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: string;
        composedFace: boolean;
        constantEffect?: undefined;
        summonRitual?: undefined;
        talentEffect?: undefined;
        subcategory?: undefined;
        hidden?: undefined;
    } | {
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: any;
        constantEffect: string;
        composedFace: boolean;
        summonRitual?: undefined;
        talentEffect?: undefined;
        subcategory?: undefined;
        hidden?: undefined;
    } | {
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: any;
        summonRitual: number;
        composedFace: boolean;
        constantEffect?: undefined;
        talentEffect?: undefined;
        subcategory?: undefined;
        hidden?: undefined;
    } | {
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: any;
        talentEffect: string;
        composedFace: boolean;
        constantEffect?: undefined;
        summonRitual?: undefined;
        subcategory?: undefined;
        hidden?: undefined;
    } | {
        name: string;
        power: number;
        category: string;
        subcategory: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: any;
        talentEffect: string;
        composedFace: boolean;
        constantEffect?: undefined;
        summonRitual?: undefined;
        hidden?: undefined;
    } | {
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: any;
        hidden: boolean;
        composedFace: boolean;
        constantEffect?: undefined;
        summonRitual?: undefined;
        talentEffect?: undefined;
        subcategory?: undefined;
    })[];
    babyDragonDef: {
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: any;
        composedFace: boolean;
    };
    cubicDragonDef: {
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: any;
        composedFace: boolean;
    };
    /** Renomes de carta: baralhos antigos. */
    cardRenameMap: Readonly<Record<string, string>>;
    resolveCardName(name: string): string;
    dragonTokenDef(name: any): {
        name: string;
        power: number;
        category: string;
        abilityType: string;
        abilityName: string;
        abilityDesc: string;
        onDestroy: any;
        onEnter: any;
        composedFace: boolean;
    };
};
export { DfData };
export type DfDataApi = typeof DfData;
